### PR TITLE
Possible typo? input → output

### PR DESCRIPTION
**Pull request by exogen**
Not sure if this is a typo or not, but "returning an input" seemed wrong to me.

### CODE REVIEW

**Comment by divmain** [comment]
Hmm... in my head, it is correct as written 😄 But this should be reworded if it wasn't immediately clear what I was talking about.  The idea I'm attempting to communicate is that pluggables are equivalent in spirit to:

``` javascript
function fn (some, inputs) {
  var delegated = otherFn(some);
  // ... calculate output value
  return outputValue;
}
```

**Comment by exogen** [comment]
Sorry, I still don't really understand – in what sense is your example returning an _input_?

**Comment by divmain** [comment]
I should've read your diff better.  You're right, I'm blind... and thankful.

**Comment by divmain** [comment]
Thanks @exogen :P

**Pull request merged**
